import { ModelCatalogEntry } from './types';

/**
 * Vichith AI Runtime - Model Registry
 * 
 * Maps internal Model IDs to their NVIDIA VRAM requirements, quantization,
 * NVMe hot-swap capability, credit cost per minute, and fallback models.
 */
export const VICHITH_MODEL_REGISTRY: Record<string, ModelCatalogEntry> = {
  'vch-ai-denoise-v1': {
    modelId: 'vch-ai-denoise-v1',
    name: 'Vichith DeepVoice Denoise (FP16)',
    providerFamily: 'PyTorch / CUDA',
    version: '1.2.0',
    supportedCapabilityIds: ['cap:video_denoise_audio'],
    requiredVramGb: 8,
    quantization: 'fp16',
    maxContextTokensOrFrames: 10000,
    creditCostPerMinute: 15,
    preferredProviders: ['e2e_networks', 'runpod', 'local_studio'],
    fallbackModelIds: ['vch-ai-denoise-lite'],
    isHotSwapCapable: true,
    deprecationStatus: 'active',
  },
  'vch-ai-denoise-lite': {
    modelId: 'vch-ai-denoise-lite',
    name: 'Vichith DeepVoice Denoise Lite (INT8)',
    providerFamily: 'PyTorch / TensorRT',
    version: '1.2.0',
    supportedCapabilityIds: ['cap:video_denoise_audio'],
    requiredVramGb: 4,
    quantization: 'int8',
    maxContextTokensOrFrames: 10000,
    creditCostPerMinute: 8,
    preferredProviders: ['e2e_networks', 'runpod', 'local_studio'],
    fallbackModelIds: [],
    isHotSwapCapable: true,
    deprecationStatus: 'active',
  },
  'vch-rife-fps-60': {
    modelId: 'vch-rife-fps-60',
    name: 'Vichith RIFE Optical Flow 60FPS (FP16)',
    providerFamily: 'PyTorch / CUDA',
    version: '4.13.0',
    supportedCapabilityIds: ['cap:video_frame_interpolate_60fps'],
    requiredVramGb: 16,
    quantization: 'fp16',
    maxContextTokensOrFrames: 3000,
    creditCostPerMinute: 30,
    preferredProviders: ['e2e_networks', 'runpod'],
    fallbackModelIds: ['vch-rife-lite-12gb'],
    isHotSwapCapable: true,
    deprecationStatus: 'active',
  },
  'vch-rife-lite-12gb': {
    modelId: 'vch-rife-lite-12gb',
    name: 'Vichith RIFE Optical Flow Lite (FP16)',
    providerFamily: 'PyTorch / CUDA',
    version: '4.13.0',
    supportedCapabilityIds: ['cap:video_frame_interpolate_60fps'],
    requiredVramGb: 12,
    quantization: 'fp16',
    maxContextTokensOrFrames: 3000,
    creditCostPerMinute: 20,
    preferredProviders: ['e2e_networks', 'runpod', 'local_studio'],
    fallbackModelIds: [],
    isHotSwapCapable: true,
    deprecationStatus: 'active',
  },
  'vch-upscale-4k': {
    modelId: 'vch-upscale-4k',
    name: 'Vichith RealESRGAN 4K Super-Resolution',
    providerFamily: 'PyTorch / CUDA',
    version: '3.0.0',
    supportedCapabilityIds: ['cap:video_super_resolution_4k'],
    requiredVramGb: 20,
    quantization: 'fp16',
    maxContextTokensOrFrames: 2000,
    creditCostPerMinute: 40,
    preferredProviders: ['runpod', 'e2e_networks'],
    fallbackModelIds: ['vch-upscale-1080p'],
    isHotSwapCapable: true,
    deprecationStatus: 'active',
  },
  'vch-genai-video-v1': {
    modelId: 'vch-genai-video-v1',
    name: 'Vichith Video Diffusion (Hunyuan / LTX-Video)',
    providerFamily: 'Diffusion PyTorch',
    version: '1.0.0',
    supportedCapabilityIds: ['cap:video_generate_broll'],
    requiredVramGb: 40,
    quantization: 'bf16',
    maxContextTokensOrFrames: 121,
    creditCostPerMinute: 80,
    preferredProviders: ['runpod'],
    fallbackModelIds: [],
    isHotSwapCapable: false, // Routes to Tier 2 Serverless Scale-to-Zero Pod
    deprecationStatus: 'active',
  },
  'vch-whisper-large-v3': {
    modelId: 'vch-whisper-large-v3',
    name: 'OpenAI Whisper Large v3 (FP16)',
    providerFamily: 'Transformer / CUDA',
    version: '3.0.0',
    supportedCapabilityIds: ['cap:speech_to_subtitles'],
    requiredVramGb: 10,
    quantization: 'fp16',
    maxContextTokensOrFrames: 25000,
    creditCostPerMinute: 12,
    preferredProviders: ['e2e_networks', 'runpod', 'local_studio'],
    fallbackModelIds: ['vch-whisper-base'],
    isHotSwapCapable: true,
    deprecationStatus: 'active',
  },
  'vch-whisper-base': {
    modelId: 'vch-whisper-base',
    name: 'OpenAI Whisper Base (INT8)',
    providerFamily: 'Transformer / CUDA',
    version: '3.0.0',
    supportedCapabilityIds: ['cap:speech_to_subtitles'],
    requiredVramGb: 4,
    quantization: 'int8',
    maxContextTokensOrFrames: 25000,
    creditCostPerMinute: 5,
    preferredProviders: ['e2e_networks', 'runpod', 'local_studio'],
    fallbackModelIds: [],
    isHotSwapCapable: true,
    deprecationStatus: 'active',
  },
};

export function getModelMetadata(modelId: string): ModelCatalogEntry | undefined {
  return VICHITH_MODEL_REGISTRY[modelId];
}
